// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"app/domain"
	"app/repository/repo_user"
	"app/service/service_auth"
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from injector_auth.go:

func InitializedAuth(db *gorm.DB, logger *logrus.Logger) *service_auth.ServiceAuth {
	repository := repo_user.NewRepository(db)
	serviceAuth := service_auth.NewService(logger, repository)
	return serviceAuth
}

// injector_auth.go:

var newSetUserRepository = wire.NewSet(repo_user.NewRepository, wire.Bind(
	new(domain.RepositoryUser),
	new(*repo_user.Repository),
),
)
